dlfcn-win32/dlfcn-win32

Makefile

or else the rule is applied to libdl.dll AND libdl.dll.a:
x86_64-w64-mingw32-gcc -Wl,--out-implib,libdl.dll.a -shared -o libdl.dll dlfcn.o
x86_64-w64-mingw32-gcc -Wl,--out-implib,libdl.dll.a -shared -o libdl.dll.a dlfcn.o

only one rule to generate shared/export lib

---

CMakeLists.txt

it's used to set release flags

set CMAKE_BUILD_TYPE default

---

dlfcn.c

Added support for unicode character set.
In the revised code, both unicode and multibyte are supported. 
test.c and testdll.c are used for test. 
Tested under VS2012, with both unicode and multibyte settings. Test passed.
Also tested under Cygwin, using minGW-gcc compiler (x86_64-w64-mingw32-gcc-4.8.2.exe). Test passed.

Added support for unicode character set.

---

.gitignore
Makefile
configure

instead of /tmp/ to avoid races when building for multiple targets.

configure: put test.{c,dll} to current directory

---

CMakeLists.txt
dlfcn-win32-config.cmake.in

This simplifies the use of the library for third-party CMake user, that just need to add a:
~~~
find_package(dlfcn-win32 REQUIRED)
...
target_link_libraries(<lib> dlfcn-win32::dl)
~~~
to use this library in their cmake project.
Furthermore this automatically links correctly the `Debug` or `Release` version depending on the configuration chosen by the downstream project in Visual Studio.
To get more info on CMake package config, check: https://cmake.org/cmake/help/v3.5/manual/cmake-packages.7.html .
Besides generating an additonal file, nothing else should change in the library.

Add CMake code to export a CMake config file

---

.appveyor.yml

Apparently AppVeyor was ignoring the `build_script` section and building the [visual-studio/12/dlfcn-win32.sln](../blob/e37edf0e894c0db8c09b2aed3a3ef7504d56baf4/visual-studio/12/dlfcn-win32.sln) solution instead as its fallback of the `build` section not being defined. Setting the latter to `off` here would probably have been good enough though.

Minor AppVeyor configuration cleanup

---

dlfcn.c
test.c

According to the specs, a second consecutive call to dlerror should always return NULL .
This was the case in dlfcn-win32 before https://github.com/dlfcn-win32/dlfcn-win32/pull/20 introduce a regression that caused dlerror to crash on the second consecutive call.
In this commit the issue is fixed as suggested in https://github.com/dlfcn-win32/dlfcn-win32/issues/34 and a regression test has been added.
Fix #34 . 
cc @TimothyGu @Fishkin @xantares @robertwgh

Fix bug in dlerror second consecutive call

---

.appveyor.yml

Based on https://github.com/dlfcn-win32/dlfcn-win32/pull/46 .

Add MinGW and MinGW-w64 builds to AppVeyor (take 2)

---

.appveyor.yml
dlfcn.c

There are lot of #ifdefs which can be removed by providing one implementation which works for both MultiByte and Unicode builds.

Simplify UNICODE build

---

dlfcn.c

Documentation says: In particular, it is unsafe to take an arbitrary system
error code returned from an API and use FORMAT_MESSAGE_FROM_SYSTEM without
FORMAT_MESSAGE_IGNORE_INSERTS.

Call FormatMessage() with FORMAT_MESSAGE_IGNORE_INSERTS

---

test.c

Otherwise running test show GUI error messages which needs to be closed.

Turn off GUI error messages around LoadLibraryA also in test

---

dlfcn.c

malloc() may fail, so propagate this error to caller.

Correctly process malloc() error in dlsym()

---

dlfcn.c

It does not make sense to pass file variable (which is NULL) to function
save_err_ptr_str() which converts its argument to string. We can call
directly save_err_str() with string value.
Also it is highly unexpected that GetModuleHandle(NULL) call fails.

Show "(null)" in error message when passed filname to dlopen() was NULL and error occurred

---

dlfcn.c

Usage of VirtualQueryEx() call is needed for retrieving HMODULE of passed
function address and it is just an undocumented hack. Based on @rhabacker's
tests it is unstable and does not work correctly.
https://github.com/dlfcn-win32/dlfcn-win32/pull/72#issuecomment-656581418
So replace VirtualQueryEx() call by standard GetModuleHandleExA() function
with special GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS flag which should do
the same thing but it is documented and it is working correctly.

Replace VirtualQueryEx() call by GetModuleHandleExA() call

---

dlfcn.c

This change should fix following compile error:
dlfcn.c: In function 'dlsym':
dlfcn.c:374:14: warning: implicit declaration of function 'GetModuleHandleExA'
dlfcn.c: undefined reference to `GetModuleHandleExA'
Documentation for function GetModuleHandleExA() says:
To compile an application that uses this function, define _WIN32_WINNT as 0x0501 or later.
Fixes: https://github.com/dlfcn-win32/dlfcn-win32/issues/75

Fix compilation with older environments

---

.appveyor.yml

This change no function effect as it changes only order of defined
variables. The only visible change is on appveyor web where variables are
printed in other as they are defined. If list of variables is too long,
variables defined later are hidden on the web interface. Variable
APPVEYOR_BUILD_WORKER_IMAGE was moved to the end of list as it is less
important to know as variable GENERATOR (defines which compiler is used).

Change order of variables in appveyor build matrix

---

.travis.yml
tools/ci-build.sh

Beware that i586-mingw32msvc-gcc is sometimes just a symlink to
i686-w64-mingw32-gcc. Real i586-mingw32msvc-gcc compiler is available in
mingw32 package only in dist trusty.

Run Travis tests also under i586-mingw32msvc-gcc compiler

---

tests/test.c

* warning C4996: '_open': This function or variable may be unsafe.
* warning C4996: 'strerror': This function or variable may be unsafe.
* warning C4996: 'wcscpy': This function or variable may be unsafe.
* warning C4996: '_wopen': This function or variable may be unsafe.

Add _CRT_SECURE_NO_WARNINGS for test.c to disable MSVC deprecation warnings

---

src/dlfcn.c

sprintf() is marked by MSVC as unsafe and suppressing compile warning does
not work. It is still generated on AppVeyor. So rewrite code for converting
pointer number to string via open coded for-loop and do not use unsafe
sprintf() function anymore. New code correctly handles both 32bit and 64bit
variants and does not use any #ifdef _MSC_VER anymore.

Rewrite function save_err_ptr_str() to not use sprintf()

---

src/dlfcn.c
tests/test.c

This pull request contains various fixes for different MSVC and gcc compilers, different Windows versions and also for different compile environment (WDK, _WIN32_WINNT, ...). With these changes, dlfcn-win32 compiles without issues also in Visual Studio 6.0, also in WDK 6001.18002 and also for Windows 7 (K32EnumProcessModules). Compiled library/executable should have same functionality independently of used compiler and chosen target environment.

Various fixes

---

src/dlfcn.c
src/dlfcn.h

on unix the addr argument seems to be const
fix that for consistency

dladdr: const void *addr

---

CMakeLists.txt

Silents warnings, cmake 3.2 is available in distros since many years

CMake: Bump version

---

src/dlfcn.c

Use GetProcAddress() wrapper as SetThreadErrorMode() is not available on older Windows versions.

Prefer usage of thread-safe function SetThreadErrorMode() instead of process-global function SetErrorMode()

---

src/CMakeLists.txt

When using the CMake wrapper from Meson the build fails, as the `include` directory does not get recognized.
This patch here is the common CMake way of linking header files to a library. Most projects would use `$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>` as the headers are commonly placed there. Moving the header might be worth considering, but as it stands it works just fine.

Fix CMake include directive when using wrappers like meson.

---

src/dlfcn.c

Number is stored in NumberOfRvaAndSizes and it may be less than IMAGE_NUMBEROF_DIRECTORY_ENTRIES.

Add missing check that section index in get_image_section() is valid

---

CMakeLists.txt

Fix https://github.com/dlfcn-win32/dlfcn-win32/issues/116 .

Fix compatibility with CMake 4.0 by bumping policy_max in cmake_minimum_required to 3.10 

---

src/dlfcn.c
tests/CMakeLists.txt
tests/test-dladdr.c
tests/test.c

This code was originally contributed by @pali . Please see individual commits for more details.
Fix https://github.com/dlfcn-win32/dlfcn-win32/issues/115 .
Part of this changes allow to `dlsym(RTLD_NEXT, "malloc")`, solving https://github.com/dlfcn-win32/dlfcn-win32/issues/112 . This will be possible unless `_DEBUG` is defined, as in that case `malloc` continues to be used.

Remove use of CRT, fix gcc compilation in C++ mode, fix missing includes and fix warnings
